### PR TITLE
Add ConfigureAwait(false) to avoid deadlocks

### PR DESCRIPTION
**Pull request by jnettleton**
#31 Library should use ConfigureAwait(false) on all await method calls to avoid deadlocks

### CODE REVIEW

**Comment by clemensv** [comment]
Sorry about not getting to this far earlier. I agree with this being a good change, even though the runtime context won't ever have a sync context where this will be an issue. Could you rebase on the current state of master?

**Comment by jnettleton** [comment]
Update complete.

**Comment by clemensv** [comment]
Your PR should only have the three commits (ideally squashed) on top of the head of master.

**Comment by jnettleton** [comment]
I'm not as proficient with git rebase and squash yet.  It looks like I squashed my 3 commits.  what's required for the next step?  do I need to squash the other ones (after I rebased on the current state of master)?

**Comment by clemensv** [comment]
@jnettleton I cherry-picked your commits onto the top of HEAD of master and put them into the "asynccfgawait" branch here. Can you please fetch that and force update your PR branch with it? The integration tests don't seem to be working with the changes, however.

**Comment by jnettleton** [comment]
after updating my repo with upstream, I got an error: Main and Release CI Build: All jobs have failed.  The 2 failing tests (TcpBridge, UdpBridge) were previously skipped (with [Fact(Skip = "true")])

[build (windows-latest)](https://github.com/jnettleton/azure-relay-bridge/actions/runs/3096259720/jobs/5011606306#logs)

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.87]     Microsoft.Azure.Relay.Bridge.Test.BridgeTest.UdpBridge [FAIL]
[xUnit.net 00:00:00.88]     Microsoft.Azure.Relay.Bridge.Test.BridgeTest.TcpBridgeBadListener [SKIP]
[xUnit.net 00:00:00.88]     Microsoft.Azure.Relay.Bridge.Test.BridgeTest.TcpBridge [FAIL]
  Failed Microsoft.Azure.Relay.Bridge.Test.BridgeTest.UdpBridge [6 ms]
  Error Message:
   System.InvalidOperationException : The AZBRIDGE_TEST_CXNSTRING environment string must be set to a preconfigured Relay namespace for this test to execute

**Comment by jnettleton** [comment]
CI build on my repo succeeded.  not sure how to run checks again.

**Comment by jnettleton** [comment]
after I rebased with master, I got an unexpected build error in the TcpClient unit test:

Failed Microsoft.Azure.Relay.Bridge.Test.BridgeTest.TcpBridge [671 ms]
  Error Message:
   Assert.Equal() Failure
   Expected: Hello!
   Actual:   (null)
   
I recommend a short delay after sending the data in the TcpBridge and UdpBridge tests to allow for a context switch as shown:

    w.WriteLine("Hello!");
    w.Flush();
    Thread.Sleep(1);

I could create a separate issue for this suggestion if you prefer.

**Pull request merged**
